import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { BackgroundGradientAnimation } from "@/components/ui/bg-gradient-animation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>AI Steel Weight Calculator | Metal Zone</title>
        <link rel="icon" href="favicon.ico" sizes="any" />
        <meta name="title" content="AI Steel Weight Calculator" />
        <meta
          name="description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />

        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://calculator.metalzoneuae.com/"
        />
        <meta property="og:title" content="AI Steel Weight Calculator" />
        <meta
          property="og:description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />
        <meta
          property="og:image"
          content="https://calculator.metalzoneuae.com/ss.png"
        />

        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://calculator.metalzoneuae.com/"
        />
        <meta property="twitter:title" content="AI Steel Weight Calculator" />
        <meta
          property="twitter:description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />
        <meta
          property="twitter:image"
          content="https://calculator.metalzoneuae.com/ss.png"
        />
      </head>
      <body className={inter.className + " flex flex-col items-center"}>
        <div className="z-0 h-screen w-screen absolute blur-2xl">
          <BackgroundGradientAnimation />
        </div>
        <div className="z-10 bg-[rgba(0,0,0,0.5)] w-screen h-screen backdrop-filter backdrop-blur-sm">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
