import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>AI Steel Weight Calculator | Metal Zone</title>
        <link rel="icon" href="favicon.ico" sizes="any" />
        <meta name="title" content="AI Steel Weight Calculator" />
        <meta
          name="description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />

        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://calculator.metalzoneuae.com/"
        />
        <meta property="og:title" content="AI Steel Weight Calculator" />
        <meta
          property="og:description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />
        <meta
          property="og:image"
          content="https://calculator.metalzoneuae.com/ss.png"
        />

        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://calculator.metalzoneuae.com/"
        />
        <meta property="twitter:title" content="AI Steel Weight Calculator" />
        <meta
          property="twitter:description"
          content="AI powered steel weight calculator by Metal Zone General Trading LLC"
        />
        <meta
          property="twitter:image"
          content="https://calculator.metalzoneuae.com/ss.png"
        />
      </head>
      <body className={inter.className + " flex flex-col items-center"}>
        <div className="z-0 h-screen w-screen absolute blur-2xl">
          <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
            <path
              fill="#FF8B31"
              d="M42.2,-16.1C48.1,4.7,42,27,23.3,43.2C4.6,59.3,-26.5,69.4,-46.5,56.6C-66.5,43.9,-75.3,8.3,-65.7,-17.6C-56.1,-43.4,-28,-59.4,-5,-57.8C18.1,-56.2,36.2,-36.9,42.2,-16.1Z"
              transform="translate(100 100)"
            />
          </svg>
        </div>
        <div className="z-10 bg-[rgba(0,0,0,0.5)] w-screen h-screen backdrop-filter backdrop-blur-sm">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
